# Generated by Django 4.2.7 on 2023-12-07 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=False, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
