# Generated by Django 4.2.7 on 2023-12-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bidhistory_comments_listing_listings_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=10), max_digits=10),
        ),
    ]
