# Generated by Django 4.2.7 on 2023-12-11 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listings_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
