# Generated by Django 4.2.7 on 2023-12-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bidhistory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidhistory',
            name='bid_amount',
        ),
    ]
